# Hypotheses and expectations

My hypothesis is that if foreign contacts including European and Chinese had impact on the emergence of social inequality in local indigenous society due to the monopolies for trade between a small number of indigenous people, then I expect to see the changes in social organization from a more corporate to a more network organization that can be reflected by pottery production at Kiwulan. The emergence of craft specialization, here pottery specialization, are usually related to the presence of elite control. In this case, if the competitions for foreign resources and being trade partners of European or Chinese colonizer among individuals gradually lead to the emergence of social inequality, then I expect the local pottery will show more homogeneous features after contact due to the pottery specialization caused by control of small group of individuals.

# Part of Introdution

In this paper, we use EFA for pottery shape analysis to evaluate the level of standardization of pottery from an Iron Age site in northeastern Taiwan in relation to the European presence in the 17th century that might hint the emergence of craft specialization for pottery production. Craft specialization can provide further evidence about the type of production organization which is closely related to economic or political aspects of society [@Arnold2000; @Blackman1993; @Costin1991; @Hirshman2010; @Stark1995]. The emergence of craft specialization can also be an indicator of social inequality that hints the possibility of the presence of production groups worked for specific individuals. The presence of craft specialization is commonly studied by measuring the standardization of ceramics based on the assumption that the specialized mass production will lead to uniformity or homogeneity of the product due to increased skills, routinization, and lower diversity of producers [@Arnold2000]. To test the prediction of a shift in the level of social inequality in this case study in northeastern Taiwan influenced by the colonial European presence, we use standardization of pottery in shapes as an index for craft specialization to identify the presence of a few individuals controlling large scale pottery production [@Costin1995; @Hirshman2010] using outline-based geometric morphometrics couples with traditional metric measurements to compare and evaluate the use of outline approaches for pottery with high consistency in shapes. 
