on: [push, pull_request]

jobs:
  run-dockerfile:
    runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Build the Docker image
            run: docker build . --file Dockerfile
